sudo: required
services:
  - docker
before_install:
  - docker build -t kehtabp/frontend -f Dockerfile.dev .
script:
  - docker run -e CI=true kehtabp/frontend npm run test
before_deploy:
  - openssl aes-256-cbc -K $encrypted_f2356db65f28_key -iv $encrypted_f2356db65f28_iv -in deploy_rsa.enc -out deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: docker -v
  on:
    branch: master